### ISSUE TITLE
Should GsSession>>logout signal an error if not logged in?

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/SparkleFFI#12]
GsSessionTest>>testLogoutWhenNotLoggedIn expects an Error to be signaled if not logged in. No error is signaled, so this test fails. No other senders of #logout have handlers for this error. The fix for #11 made #logout answer true upon success, but this may not be the best answer.

It seem like it would be better to return self upon success, and signal an exception (though perhaps not an Error, perhaps a Notification?) upon an attempt to logout a not-logged-in session.

Leaving this one unfixed for now, pending design discussion.

**Comment by nrgiii** [comment]
GsSession>>logout will now raise and Error if the receiver was not logged in. Unit test added.
