### ISSUE TITLE
Need smalltalk logic to call thread safe library GciTsNbLogout

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/SparkleFFI#16]
The Non-blocking logout for a thread safe gci library would be handy because it doesn't wait for a reply from the server. Currently, the GemStoneFFI smalltalk package only implements `gciTsLogout:gsError:` and not the non-blocking variant  as far as I can tell. 

Currently, when using RSR through the gci library, if a gcli logout gets in trouble, the pharo image will hang. 

See: 
GciThreadSafeInterface>>#logout
GciThreadSafeInterface>>#logoutNoError
GciThreadSafeInterface>>#gciTsLogout:gsError:

**Comment by nrgiii** [comment]
Code added to v.1.1 . See GsSession>>logoutNbNoError
