### ISSUE TITLE
Improvement in error handling if image forcibly killed and session is gone

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/SparkleFFI#2]
When connected through the SparkleFFI interface in Pharo sometimes the image will hang if an error occurs in the server. While that's not a SparkleFFI bug, one does have to force quit the Pharo image. 

If you're logged in through the FFI, and the image has to be forcibly killed, restarting the image will leave a stale session hanging around. The Connections Launcher isn't mature enough to know how to detect stale sessions and so hitting disconnect on a bad session will still try to send `logout` to the instance of `GciThreadSafeInterface`. (The connection launcher should eventually know how to detect stale sessions earlier.) 

When sending `logout`, sometimes one will get a walkback in `GciThreadSafeInterface>>logoutNoError:` because it seems `result` is the `GciError` class and the method sends `signal:` to it. It would be helpful if we didn't get a walkback. 

Not a high priority as one can login again after closing the Pharo walkback. 

![image](https://user-images.githubusercontent.com/36212516/110857836-2b55f880-826e-11eb-85dd-d3f82fa4f8aa.png)

**Comment by nrgiii** [comment]
Fix this issue by tracking sessions in GsSession>>AllSessions class var and ignore the logout message for stale sessions.
Add an image startup hook to clear out stale sessions.
