### ISSUE TITLE
SparkleFFI package names should have a `SparkleFFI-` prefix ...

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/SparkleFFI#3]
... in Pharo, you kinda expect that the project name is in the name of the package, since there is no project-oriented view in the _Package_ browser

**Comment by martinmcclure** [comment]
We could also rename the project GemStoneFFI. So far, the only user of it is Sparkle, but IIUC it is intended to be a generic interface to the GCI.

**Comment by kurtkilpela** [comment]
A better name might be GemStoneGCIForPharo or PharoGCI.

**Comment by martinmcclure** [comment]
Project renamed to Pharo-GemStoneFFI
